// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: presence.proto

package presencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Presence_GetPresence_FullMethodName           = "/relay.presence.v1.Presence/GetPresence"
	Presence_StreamChannelPresence_FullMethodName = "/relay.presence.v1.Presence/StreamChannelPresence"
)

// PresenceClient is the client API for Presence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Presence is the thin internal presence service (spec/04-dependencies.md §8): one unary
// RPC and one server-streaming RPC, the same proto across all five languages.
type PresenceClient interface {
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*PresenceStatus, error)
	StreamChannelPresence(ctx context.Context, in *StreamChannelPresenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PresenceStatus], error)
}

type presenceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceClient(cc grpc.ClientConnInterface) PresenceClient {
	return &presenceClient{cc}
}

func (c *presenceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*PresenceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceStatus)
	err := c.cc.Invoke(ctx, Presence_GetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceClient) StreamChannelPresence(ctx context.Context, in *StreamChannelPresenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PresenceStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Presence_ServiceDesc.Streams[0], Presence_StreamChannelPresence_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChannelPresenceRequest, PresenceStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Presence_StreamChannelPresenceClient = grpc.ServerStreamingClient[PresenceStatus]

// PresenceServer is the server API for Presence service.
// All implementations must embed UnimplementedPresenceServer
// for forward compatibility.
//
// Presence is the thin internal presence service (spec/04-dependencies.md §8): one unary
// RPC and one server-streaming RPC, the same proto across all five languages.
type PresenceServer interface {
	GetPresence(context.Context, *GetPresenceRequest) (*PresenceStatus, error)
	StreamChannelPresence(*StreamChannelPresenceRequest, grpc.ServerStreamingServer[PresenceStatus]) error
	mustEmbedUnimplementedPresenceServer()
}

// UnimplementedPresenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServer struct{}

func (UnimplementedPresenceServer) GetPresence(context.Context, *GetPresenceRequest) (*PresenceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedPresenceServer) StreamChannelPresence(*StreamChannelPresenceRequest, grpc.ServerStreamingServer[PresenceStatus]) error {
	return status.Error(codes.Unimplemented, "method StreamChannelPresence not implemented")
}
func (UnimplementedPresenceServer) mustEmbedUnimplementedPresenceServer() {}
func (UnimplementedPresenceServer) testEmbeddedByValue()                  {}

// UnsafePresenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServer will
// result in compilation errors.
type UnsafePresenceServer interface {
	mustEmbedUnimplementedPresenceServer()
}

func RegisterPresenceServer(s grpc.ServiceRegistrar, srv PresenceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Presence_ServiceDesc, srv)
}

func _Presence_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Presence_GetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presence_StreamChannelPresence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChannelPresenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PresenceServer).StreamChannelPresence(m, &grpc.GenericServerStream[StreamChannelPresenceRequest, PresenceStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Presence_StreamChannelPresenceServer = grpc.ServerStreamingServer[PresenceStatus]

// Presence_ServiceDesc is the grpc.ServiceDesc for Presence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Presence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.presence.v1.Presence",
	HandlerType: (*PresenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPresence",
			Handler:    _Presence_GetPresence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChannelPresence",
			Handler:       _Presence_StreamChannelPresence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "presence.proto",
}
