# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: presence.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epresence.proto\x12\x11relay.presence.v1\"%\n\x12GetPresenceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"0\n\x1cStreamChannelPresenceRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\"1\n\x0ePresenceStatus\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08\x32\xd2\x01\n\x08Presence\x12W\n\x0bGetPresence\x12%.relay.presence.v1.GetPresenceRequest\x1a!.relay.presence.v1.PresenceStatus\x12m\n\x15StreamChannelPresence\x12/.relay.presence.v1.StreamChannelPresenceRequest\x1a!.relay.presence.v1.PresenceStatus0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRESENCEREQUEST']._serialized_start=37
  _globals['_GETPRESENCEREQUEST']._serialized_end=74
  _globals['_STREAMCHANNELPRESENCEREQUEST']._serialized_start=76
  _globals['_STREAMCHANNELPRESENCEREQUEST']._serialized_end=124
  _globals['_PRESENCESTATUS']._serialized_start=126
  _globals['_PRESENCESTATUS']._serialized_end=175
  _globals['_PRESENCE']._serialized_start=178
  _globals['_PRESENCE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
