# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from relay.presence import presence_pb2 as presence__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in presence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPresence = channel.unary_unary(
                '/relay.presence.v1.Presence/GetPresence',
                request_serializer=presence__pb2.GetPresenceRequest.SerializeToString,
                response_deserializer=presence__pb2.PresenceStatus.FromString,
                _registered_method=True)
        self.StreamChannelPresence = channel.unary_stream(
                '/relay.presence.v1.Presence/StreamChannelPresence',
                request_serializer=presence__pb2.StreamChannelPresenceRequest.SerializeToString,
                response_deserializer=presence__pb2.PresenceStatus.FromString,
                _registered_method=True)


class PresenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPresence(self, request, context):
        """unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChannelPresence(self, request, context):
        """server-streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPresence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresence,
                    request_deserializer=presence__pb2.GetPresenceRequest.FromString,
                    response_serializer=presence__pb2.PresenceStatus.SerializeToString,
            ),
            'StreamChannelPresence': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChannelPresence,
                    request_deserializer=presence__pb2.StreamChannelPresenceRequest.FromString,
                    response_serializer=presence__pb2.PresenceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay.presence.v1.Presence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relay.presence.v1.Presence', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Presence(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relay.presence.v1.Presence/GetPresence',
            presence__pb2.GetPresenceRequest.SerializeToString,
            presence__pb2.PresenceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChannelPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/relay.presence.v1.Presence/StreamChannelPresence',
            presence__pb2.StreamChannelPresenceRequest.SerializeToString,
            presence__pb2.PresenceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
